export const siteConfig = {
  name: "Benz Yuthapum | Developer Portfolio",
  authorName: "Benz Yuthapum",
  username: "benzyuthapum",
  description: "Benz Yuthapum's portfolio.",
  url: "https://nbarkiya.xyz",
  links: {
    // twitter: "https://x.com/namanbarkiya",
    github: "https://github.com/Yuthapump",
  },
  ogImage: "public/student-img.png",
  iconIco: "/favicon.ico",
  logoIcon: "/favicon.ico",
  keywords: [
    "Benz Yuthapum",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
